### ISSUE TITLE
additionalProperties should be required

### ISSUE THREAD

**Issue by dan-pulley** [aarondl/oa3#12]
there's a weird situation with additionalProperties.

```yaml
    SomeType:
      type: object
      properties:
        gets_a_type:
          type: object
        weird_hack:
          type: object
          additionalProperties:
            oneOf:
              - type: string
```

the above schema generates

```go
type SomeType struct {
	GetsAType SomeTypeGetsAType `json:"gets_a_type,omitempty"`
	WeirdHack map[string]any    `json:"weird_hack,omitempty"`
}
```

what i would expect:
- WeirdHack to not work at all
- GetsAType to be an empty struct or something as it has no properties
- additionalProperties to be required to get the outcome i want
- a way to specify an inline map[string]any, a type is overkill imo

generally, additionalProperties support seems a bit weird.
